### ISSUE TITLE
Segfault on playing movie

### ISSUE THREAD

**Issue by virus-found** [Baughn/Dwarf-Fortress--libgraphics-#8] opened 2009-07-08 21:51 UTC
6408ea26e commit.
If [INTRO:ON] is set, immediately after playing the first "Beyond quality" movie I receive this:
./df: line 12:  2659 Segmentation fault      ./dwarfort.exe $*

**Comment by Baughn** [comment] 2009-07-09 09:22
Nope, can't reproduce. Does this happen consistently? In print-mode standard?

**Comment by virus-found** [comment] 2009-07-09 10:04
It's fixed in 2cb63c1a11 (doesn't crash with either of mentioned below init.txts)
It didn't crash in 6408ea26e with a stock init.txt
It crashed in 6408ea26e with such diff to a stock init.txt:
--- df/data/init/init.txt   2009-07-08 23:03:21.000000000 +0400
+++ df/data/init/init.txt   2009-07-09 01:28:32.000000000 +0400
@@ -15 +15 @@
-[WINDOWED:PROMPT]

+[WINDOWED:YES]

@@ -19,3 +19,3 @@
-[WINDOWEDX:640]

-[WINDOWEDY:300]

-[FONT:curses_640x300.png]

+[WINDOWEDX:1280]

+[WINDOWEDY:1024]

+[FONT:burzum.png]

@@ -47 +47 @@
-[GRID:80:25]

+[GRID:80:64]

@@ -52,2 +52,2 @@
-[PRINT_MODE:STANDARD]

-[SINGLE_BUFFER:NO]

+[PRINT_MODE:PARTIAL:0]

+[SINGLE_BUFFER:YES]

@@ -61 +61 @@
-[FPS:NO]

+[FPS:YES]

@@ -69 +69 @@
-[G_FPS_CAP:20]

+[G_FPS_CAP:50]

@@ -94 +94 @@
-[AUTOSAVE:NONE]

+[AUTOSAVE:SEASONAL]

@@ -96 +96 @@
-[AUTOSAVE_PAUSE:NO]

+[AUTOSAVE_PAUSE:YES]

@@ -100 +100 @@
-[INITIAL_SAVE:NO]

+[INITIAL_SAVE:YES]

@@ -104 +104 @@
-[PAUSE_ON_LOAD:NO]

+[PAUSE_ON_LOAD:YES]

@@ -108 +108 @@
-[EMBARK_WARNING_ALWAYS:NO]

+[EMBARK_WARNING_ALWAYS:YES]

@@ -112,7 +112,7 @@
-[SHOW_EMBARK_RIVER:FINDER]

-[SHOW_EMBARK_POOL:FINDER]

-[SHOW_EMBARK_M_PIPE:FINDER]

-[SHOW_EMBARK_M_POOL:FINDER]

-[SHOW_EMBARK_CHASM:FINDER]

-[SHOW_EMBARK_PIT:FINDER]

-[SHOW_EMBARK_OTHER:FINDER]

+[SHOW_EMBARK_RIVER:ALWAYS]

+[SHOW_EMBARK_POOL:ALWAYS]

+[SHOW_EMBARK_M_PIPE:ALWAYS]

+[SHOW_EMBARK_M_POOL:ALWAYS]

+[SHOW_EMBARK_CHASM:ALWAYS]

+[SHOW_EMBARK_PIT:ALWAYS]

+[SHOW_EMBARK_OTHER:ALWAYS]

So, this should definitely be closed.

**Comment by Baughn** [comment] 2009-07-09 10:20
Fixed in 2cb63c1a11b3df3fb7b53b152625179f9c44a6f7 (branch m1)

**Closed as completed by Baughn** 2009-07-09 10:20 UTC
